kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-postgresql-claim
  labels:
    app: keycloak-postgresql
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
