kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: keycloak-main
  labels:
    app: keycloak-database
    app.kubernetes.io/component: keycloak-database
    app.kubernetes.io/instance: keycloak-database
    template: postgresql-persistent-template
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
