apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
  - ../../../base
  - kafka
  - topics
  - prometheus-kafka-adapter
  - kafka-podmonitors.yaml
patchesStrategicMerge:
  - osc-kafdrop.yaml
