apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak
  namespace: keycloak-main
spec:
  to:
    kind: Service
    name: keycloak
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
