apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - files:
      - files/data.yaml
    name: keycloak
commonAnnotations:
  kustomize.config.k8s.io/behavior: replace
