---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: keycloak-main
  labels:
    deployment: postgresql
    app: keycloak-database
    app.kubernetes.io/component: keycloak-database
    app.kubernetes.io/instance: keycloak-database
    template: postgresql-persistent-template
spec:
  selector:
    matchLabels:
      deployment: postgresql
  template:
    metadata:
      labels:
        deployment: postgresql
    spec:
      containers:
        - name: postgresql
          image: docker.io/postgres:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
          resources:
            limits:
              memory: 512Mi
          envFrom:
            - secretRef:
                name: postgresql
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql
