apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: "keycloak-service"
spec:
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    deployment: keycloak
  sessionAffinity: ClientIP
