apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  labels:
    app: keycloak
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    deployment: keycloak
