---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: keycloak-main
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
