---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak-main
resources:
  - deployments
  - externalsecrets
  - persistentvolumeclaims
  - routes
  - secrets
  - serviceaccounts
  - services
commonLabels:
  app.kubernetes.io/name: keycloak-main
  app.kubernetes.io/component: keycloak-server
  app.kubernetes.io/part-of: auth
