---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-main
spec:
  destination:
    name: in-cluster
    namespace: keycloak-main
  project: osc-infra
  source:
    path: keycloak/overlays/osc/osc-cl3
    repoURL: https://github.com/os-climate/ops-argocd.git
    targetRevision: main
