apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  secretStoreRef:
    name: osc-vault-store
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: s3-credentials
  dataFrom:
    - extract:
        key: osc/osc-cl3/osc-ci-prow/prow-s3-credentials
