---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pachyderm
spec:
  destination:
    name: osc-cl2
    namespace: pachyderm
  project: os-climate
  source:
    path: pachyderm/overlays/osc/osc-cl2
    repoURL: https://github.com/Gregory-Pereira/ops-argocd.git
    targetRevision: setup-argocd-and-vault
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
